// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentsAndProfessors.proto

package com.example.tutorial.protos;

public interface ProfessorPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uc.mei.is.ProfessorP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string birthDate = 3;</code>
   * @return Whether the birthDate field is set.
   */
  boolean hasBirthDate();
  /**
   * <code>optional string birthDate = 3;</code>
   * @return The birthDate.
   */
  java.lang.String getBirthDate();
  /**
   * <code>optional string birthDate = 3;</code>
   * @return The bytes for birthDate.
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>optional string address = 4;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 4;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 4;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional int64 phoneNumber = 5;</code>
   * @return The phoneNumber.
   */
  long getPhoneNumber();

  /**
   * <code>repeated .uc.mei.is.StudentP students = 6;</code>
   */
  java.util.List<com.example.tutorial.protos.StudentP> 
      getStudentsList();
  /**
   * <code>repeated .uc.mei.is.StudentP students = 6;</code>
   */
  com.example.tutorial.protos.StudentP getStudents(int index);
  /**
   * <code>repeated .uc.mei.is.StudentP students = 6;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .uc.mei.is.StudentP students = 6;</code>
   */
  java.util.List<? extends com.example.tutorial.protos.StudentPOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .uc.mei.is.StudentP students = 6;</code>
   */
  com.example.tutorial.protos.StudentPOrBuilder getStudentsOrBuilder(
      int index);
}
