// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentsAndProfessors.proto

package com.example.tutorial.protos;

public interface SchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:uc.mei.is.School)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .uc.mei.is.ProfessorP professors = 1;</code>
   */
  java.util.List<com.example.tutorial.protos.ProfessorP> 
      getProfessorsList();
  /**
   * <code>repeated .uc.mei.is.ProfessorP professors = 1;</code>
   */
  com.example.tutorial.protos.ProfessorP getProfessors(int index);
  /**
   * <code>repeated .uc.mei.is.ProfessorP professors = 1;</code>
   */
  int getProfessorsCount();
  /**
   * <code>repeated .uc.mei.is.ProfessorP professors = 1;</code>
   */
  java.util.List<? extends com.example.tutorial.protos.ProfessorPOrBuilder> 
      getProfessorsOrBuilderList();
  /**
   * <code>repeated .uc.mei.is.ProfessorP professors = 1;</code>
   */
  com.example.tutorial.protos.ProfessorPOrBuilder getProfessorsOrBuilder(
      int index);
}
