// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentsAndProfessors.proto

package com.example.tutorial.protos;

public final class StudentsAndProfsProtos {
  private StudentsAndProfsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uc_mei_is_StudentP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uc_mei_is_StudentP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uc_mei_is_ProfessorP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uc_mei_is_ProfessorP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uc_mei_is_School_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uc_mei_is_School_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033StudentsAndProfessors.proto\022\tuc.mei.is" +
      "\"\207\001\n\010StudentP\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022" +
      "\021\n\tbirthDate\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\023\n\013p" +
      "honeNumber\030\005 \001(\003\022\016\n\006gender\030\006 \001(\t\022\030\n\020regi" +
      "strationDate\030\007 \001(\t\"\206\001\n\nProfessorP\022\n\n\002id\030" +
      "\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\021\n\tbirthDate\030\003 \001(\t\022\017" +
      "\n\007address\030\004 \001(\t\022\023\n\013phoneNumber\030\005 \001(\003\022%\n\010" +
      "students\030\006 \003(\0132\023.uc.mei.is.StudentP\"3\n\006S" +
      "chool\022)\n\nprofessors\030\001 \003(\0132\025.uc.mei.is.Pr" +
      "ofessorPB7\n\033com.example.tutorial.protosB" +
      "\026StudentsAndProfsProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_uc_mei_is_StudentP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uc_mei_is_StudentP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uc_mei_is_StudentP_descriptor,
        new java.lang.String[] { "Id", "Name", "BirthDate", "Address", "PhoneNumber", "Gender", "RegistrationDate", });
    internal_static_uc_mei_is_ProfessorP_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_uc_mei_is_ProfessorP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uc_mei_is_ProfessorP_descriptor,
        new java.lang.String[] { "Id", "Name", "BirthDate", "Address", "PhoneNumber", "Students", });
    internal_static_uc_mei_is_School_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_uc_mei_is_School_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uc_mei_is_School_descriptor,
        new java.lang.String[] { "Professors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
